AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - coverage/**/*
    - db/**/*
    - lib/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - spec/**/*
    - tmp/**/*
    - vendor/**/*
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - README.md
    - yarn.lock
    - .babelrc
    - .gitignore
    - .postcssrc.yml
    - .ruby-version
    - config.ru
    - package.json

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false
